### ISSUE TITLE
brew formula

### ISSUE THREAD

**Issue by orefalo** [devemio/docker-color-output#10]
Great idea, thank you so much. much better than grc!

I actually created the brew formula - 
  you shall submit the pull req on the homebrew repo or provide a tap.

Sincerely

```
class Dockercoloroutput < Formula
  desc "This package allows to colorize the docker output."
  homepage "https://github.com/devemio/docker-color-output"
  url "https://github.com/devemio/docker-color-output/archive/refs/tags/v2.0.0.tar.gz"
  version "v2.0.0"
  sha256 "f0585ec1ae03608215bcb389eb6ce4bd34f5c4409a190f80b8d59140b353933a"
  license "MIT"

  depends_on "go" => :build
  depends_on "cmake" => :build

  def install
    system "make"
    mv "bin/dco-darwin-amd64", "docker-color-output"
    bin.install "docker-color-output"
  end

  test do
    system "false"
  end
end
```

**Comment by devemio** [comment]
@orefalo wow, thanks a lot. I'll try to submit it to homebrew repo.

**Comment by orefalo** [comment]
no, no, thank you. great piece of software

you will need to provide a unit test for the brew submission to be accepted.
like a simple command line check or likes.

Sincerely,

**Comment by devemio** [comment]
@orefalo, I've created a formula as you suggested. Now it can be installed as follows:

 ```bash
brew install dldash/core/docker-color-output
```

Unfortunately, I guess I won't be able to push this to the core repository. After running the audit, one error remained:

> GitHub repository not notable enough (<30 forks, <30 watchers and <75 stars)

**Comment by devemio** [comment]
@orefalo, btw I'm not very familiar with building formulas for Homebrew. During installation it tries to download `cmake` and `go` dependencies to build a binary file. Can we distribute an already binary file at once? Is this not a good idea for brew?

**Comment by orefalo** [comment]
brew has the notion of bottles

precompiled binaries.

I am however not sure how to get this configured
