### ISSUE TITLE
Add support for filters

### ISSUE THREAD

**Issue by sManWorks** [devemio/docker-color-output#12]
When running the command like below an error is thrown

`docker ps --all --format "table {{.Names}}\t{{.RunningFor}}\t{{.Status}}\t{{.Networks}}" | docker-color-output`

    💡 Error: invalid first line  
    💥 Docker color output 2.0.1
    ⚡️ Usage:
        docker images | docker-color-output
        docker ps [-a] | docker-color-output
        docker-compose ps [-a] | docker-color-output`

I really dont care for container IDs or commands so the filter makes the output somewhat concise. Ability to add color to the filter output would be amazing

**Comment by devemio** [comment]
Now this only works with the standard column output. I will consider using custom column sets in the next version.

**Comment by devemio** [comment]
@sManWorks I have added support for a custom set of columns using `--format` option in [v2.2.0-rc.1](https://github.com/devemio/docker-color-output/releases/tag/v2.2.0-rc.1) and uploaded the binaries for mac and linux to the `Assets` section.
