### ISSUE TITLE
Update Arch Linux Package

### ISSUE THREAD

**Issue by jpbraganca** [devemio/docker-color-output#16]
The existing one is 'orphan' and is getting trouble when trying to install

**Comment by devemio** [comment]
Initially, the package for arch linux was [published](https://github.com/devemio/docker-color-output/issues/7) by @danisztls. We could kindly ask him to update it to the latest version.

You can also download the binary from the [releases](https://github.com/devemio/docker-color-output/releases) page. If you do not find a suitable one for your architecture, please let me know and I will make a build for the desired architecture and upload it.

**Comment by jpbraganca** [comment]
Thanks, thats ok. I built from src, works fine
