### ISSUE TITLE
Hi having issues with downloading from Brew

### ISSUE THREAD

**Issue by xavier-xia-99** [devemio/docker-color-output#17]
<img width="645" alt="Screenshot 2022-05-05 at 6 12 05 PM" src="https://user-images.githubusercontent.com/86207636/167033822-1ca66364-9d5f-4bdb-9dfc-a26e158178e4.png">

**Comment by devemio** [comment]
Hi, it seems you need to update Command Line tools. You can do it this way:

```bash
xcode-select --install
```

More details [here](https://stackoverflow.com/questions/52522565/git-is-not-working-after-macos-update-xcrun-error-invalid-active-developer-pa).

**Comment by xavier-xia-99** [comment]
Yep! Thank you so much!
