### ISSUE TITLE
installation for .rpm distros?

### ISSUE THREAD

**Issue by usmangt** [devemio/docker-color-output#20]
Hi,

1st of all a perfect tool that I was looking for.

Can you provide a guide on whether it is possible to install this on a .rpm (CentOS, RedHat) distribution? I cannot find this in the README.md file.

I will really like to use it on my machines.

**Comment by devemio** [comment]
Hi,

Unfortunately there is no separate `.rpm` package for CentOS / RedHat, but you can download the binary file directly from the [releases](https://github.com/devemio/docker-color-output/releases) page.

If you are using a non-amd64 architecture, please let me know and I will build a binary file for your architecture and upload it to the releases page.
