### ISSUE TITLE
OpenSSL dependancy?

### ISSUE THREAD

**Issue by gregfr** [devemio/docker-color-output#21]
Greetings

I've tried to install `docker-color-output` with Brew, but on my machine openssl@3 doesn't compile.

So I was wondering, why is there a dependency on openssl?

Thanks in advance

Regards

**Comment by devemio** [comment]
Hi,

It only uses `go` and `cmake` deps. Here is the [formulae](https://formulae.brew.sh/)](https://github.com/dldash/homebrew-core/blob/main/Formula/docker-color-output.rb#L8) for Brew. Maybe `go` uses `openssl` as a transitive dependency, but I'm not sure.

You can also download the compiled binary from the [releases](https://github.com/devemio/docker-color-output/releases/tag/v2.2.0) page. If there is no build suitable for you, please let me know, I will make a build for your architecture.

**Comment by gregfr** [comment]
Thanks for your answer.

You're perfectly right! it seems Brew tries to compile openssl@3 each time I try to do anything even unrelated. I'll continue this discussion on their forum.
The pre-compiled binary works perfectly for me, thanks a lot!

Regards
