### ISSUE TITLE
Docker Stats Support

### ISSUE THREAD

**Issue by innicoder** [devemio/docker-color-output#22]
Hi, very nice library that you have, it's really nice and shows everything with a logical coloring the only feature that I use really commonly would be `docker stats` and the small changes %5, would be yellow, the big changes in stats would be over %10..

This is just an idea, bravo for the work so far.

**Comment by devemio** [comment]
Hi, thank you 🙂

This is a good idea about `docker stats`. Please give more details about this use case.

If I understood correctly, you would like to highlight the values in the `CPU`, `MEM` columns according to the following scheme:

- `>= 5%` – yellow
- `>= 10%` – red (probably)

**Comment by devemio** [comment]
@innicoder Hi, now you can try the version with `docker stats` ([HowTo](https://github.com/devemio/docker-color-output/tree/stats?tab=readme-ov-file#-docker-stats)) 🙂

This is a beta version for now and I've attached the compiled binaries right [here](https://github.com/devemio/docker-color-output/files/14216249/docker-color-output.zip).

Please feel free to leave any feedback.
