### ISSUE TITLE
Request for Windows Compatibility

### ISSUE THREAD

**Issue by IsWladi** [devemio/docker-color-output#24]
Hello,

I am a user interested in using the 'docker-color-output' tool/library in a Windows environment. Currently, it seems that the tool is primarily designed for Unix-based systems. I would like to know if there are any plans to develop compatibility with Windows or if you could consider adding this functionality.

The ability to use 'docker-color-output' on Windows would be a great help for those in environments where Windows is the main operating system. I understand that this might require additional efforts, but I believe it would significantly broaden the scope and utility of the tool.

Is there any possibility of seeing a Windows-compatible version in the near future? Or is there any alternative way to use the tool on Windows currently?

Thank you for considering this request. I am looking forward to the future development of 'docker-color-output'.

Best regards,

**Comment by devemio** [comment]
@IsWladi Hi,

Thank you for your interest.

I have compiled a build [docker-color-output-amd64.exe.zip](https://github.com/devemio/docker-color-output/files/13598811/docker-color-output-amd64.exe.zip) for Windows from the source, but unfortunately I do not have the opportunity to test it.

Theoretically, there should be no restrictions when using in a Windows environment.

Please let me know any feedback.

**Comment by 0x326** [comment]
I ran the binary you posted and it seems to be working great!

![image](https://github.com/devemio/docker-color-output/assets/20781397/347e5528-4c9b-4f50-a32e-ba93e9abe95a)

**Comment by devemio** [comment]
@0x326 Great, thanks a lot.
