### ISSUE TITLE
Change color

### ISSUE THREAD

**Issue by kukirokuk** [devemio/docker-color-output#25]
I use tmux with a dark background color, CONTAINER ID and  COMMAND  text colors blend into the background, hard to distinguish. Is it possible to make a custom color gamma?

**Comment by devemio** [comment]
@kukirokuk Of course, you can change the color palette in version [2.4.0](https://github.com/devemio/docker-color-output/releases/tag/2.4.0) ([HowTo](https://github.com/devemio/docker-color-output?tab=readme-ov-file#-configuration))

**Comment by kukirokuk** [comment]
Thank you!
