### ISSUE TITLE
Flag to print current version / usage examples ?

### ISSUE THREAD

**Issue by jorgemxm** [devemio/docker-color-output#27]
Hi, thanks for the initiative of creating/maintaining this app, it improves docker readability!

One question, with the new feature added in v2.4.0 that allows a config file flag, 
now is not longer possible to print the current version of this application, for instance, in 2.3.0 using `docker-color-output --help` (or any other invalid flag or command) would print the application version as well as other usage examples, e.g.:
![SCR-20240209-nmvd](https://github.com/devemio/docker-color-output/assets/5948446/b499e80b-931d-40a2-bccd-86a1d92a7e3e)

Now in version 2.4.0+ , it prints the recently added flag:
![image](https://github.com/devemio/docker-color-output/assets/5948446/313daf2a-305c-4d72-b4ba-8dfd9c1d8bc0)

Have you considered this scenario for printing the app version? is there a workaround flag?
I haven't looked at the code base yet, and how the older message was being printed.... 

What are your thoughts?

**Comment by jorgemxm** [comment]
Ohh I just noticed that the message gets printed when an invalid command is passed, so... nevermind, feel free to keep open or to close :)

![image](https://github.com/devemio/docker-color-output/assets/5948446/45d1fd35-e5cd-46a4-ab60-bed18eb21ccd)

**Comment by devemio** [comment]
Hi, that's a great idea, thanks for it.

This will be added in version `2.5.1`.

<img width="492" alt="image" src="https://github.com/devemio/docker-color-output/assets/5787193/cf6573c7-3cf0-430c-b164-207b1f807e7f">

**Comment by jorgemxm** [comment]
Hi Sergey, Thanks for the Update, It works great on my end, Cheers

![image](https://github.com/devemio/docker-color-output/assets/5948446/ed1fbd9b-ca7a-4c6a-bc52-ab2f85040155)
