### ISSUE TITLE
Works but throws an error when i open terminal

### ISSUE THREAD

**Issue by CavalcanteLeo** [devemio/docker-color-output#3]
Throws this error as soon as the terminal load the alias

```
dirname: illegal option -- z
usage: dirname path
dirname: illegal option -- z
usage: dirname path
dirname: illegal option -- z
usage: dirname path
```

<img width="801" alt="Captura de Tela 2020-06-21 às 04 39 58" src="https://user-images.githubusercontent.com/1735944/85219358-64b1a580-b379-11ea-87f3-568e5a68eed0.png">

**Comment by CavalcanteLeo** [comment]
i just set the aliases like this:

```shell
alias di="~/docker-color-output/bin/docker-images"
alias dps="~/docker-color-output/bin/docker-ps"
alias dcps="~/docker-color-output/bin/docker-compose-ps"
```

worked for me, what's the purpose of `$(cd "$(dirname "$0")"; pwd -P)` ?

**Comment by devemio** [comment]
> what's the purpose of `$(cd "$(dirname "$0")"; pwd -P)` ?

It was used to determine the path where the script with aliases is located. Looks like something wrong with quotes. You can use just aliases (I think this is even preferable). Thank you for your feedback.
