### ISSUE TITLE
How to install this on the macOS

### ISSUE THREAD

**Issue by niteshkatare** [devemio/docker-color-output#9]
Hello,

how do I install this on my mac? could you please help me with the installation steps, I tried downloading both applications from the release page, not able to install either, thanks in advance.

**Comment by devemio** [comment]
Hi @niteshkatare,

Please specify which mac architecture do you use?

- You need to download the **dco-darwin-amd64** file (for Mac) from this page https://github.com/devemio/docker-color-output/releases. Actually this is already a binary file that does not require installation. You can call in the console `docker images | /path/to/dco-darwin-amd64` and it should work.
- This is not always convenient, so I prefer to create aliases. In this case, you can simply call `di`, `dps`, `dcps` commands. To add aliases, look at this example https://github.com/devemio/docker-color-output/blob/master/bash/aliases.sh. You only need to change `DOCKER_COLOR_OUTPUT_PATH` to the path to your downloaded file. These aliases should be added to the `.bashrc` or `.zshrc` file.

**Comment by niteshkatare** [comment]
Hi @devemio,

Thanks, it is working now, is there any way in bash I can suffix dco-darwin-amd64 to the docker command with the help of alias ?

**Comment by orefalo** [comment]
very nice tool - thank you so much. thumb up

Would recommend a brew formula

**Comment by orefalo** [comment]
also... it's not just BASH
ZSH & FISH are also popular shells

**Comment by devemio** [comment]
Now this app can be installed via Homebrew:

```bash
brew install dldash/core/docker-color-output
```

The `docker-color-output` command will be available in the global namespace so it will be convenient to use it in aliases.

@orefalo, thanks for the tip.
